<?php
declare(strict_types=1);

namespace cylexsky\island\modules;

use cylexsky\session\PlayerSession;

class TutorialModule extends BaseModule{

    public const LAST_TUTORIAL = 9;

    private $inTutorial;
    private $tutorialPhase;

    public function init(array $data)
    {
        parent::init($data); // TODO: Change the autogenerated stub
    }

    public function inTutorial(): bool {
        return $this->inTutorial;
    }

    public function getTutorialPhase(): int {
        return $this->tutorialPhase;
    }

    public function finishTutorial(){
        //TODO what happens when they finish the tutorial
    }

    public function progress(){
        if ($this->tutorialPhase === self::LAST_TUTORIAL){
            $this->inTutorial = false;
            $this->finishTutorial();
        }
        $this->tutorialPhase++;
    }

    public function join(PlayerSession $session){
        if (!$this->inTutorial()){
            return;
        }
        $session->getPlayer()->teleport($this->getIsland()->getWorld()->getSpawnLocation());
        $this->{"join" . $this->tutorialPhase};
    }

    public function join1(){

    }

    public function join2(){

    }

    public static function getBaseData(): array
    {
        return [true, 1];
    }

    public function save()
    {
        return $this->encodeJson([$this->inTutorial, $this->tutorialPhase]);
    }
}